language: scala
scala:
- 2.12.4
jdk:
- oraclejdk8
skip_cleanup: true
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test "$TRAVIS_TAG" != "" && test $TRAVIS_REPO_SLUG == "avast/fp-toolbox" && sbt publish
